### ISSUE TITLE
Release notes for 1.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/incubator-dbm#11]
**Release time**

`2021-07-23`

**Components involved**

- ClickHouse

**Check list**

- [x] Support query progress display DDL
- [x] Support stop running query
- [x] Add one click refresh data source
- [x] Add connection monitor
- [x] Upgrade the default versions of Vue (2.5.10 -> 2.15.3 +) and electron
- [x] Add release timeline to index
- [x] Support users to authorize users to access Clickhouse
- [x] Query history supports copying SQL
- [x] Support sql format
- [x] Support general configuration of global editor
- [x] Add software website
- [x] Support multiple query results display
- [x] Supports text query selection [Issues-13](https://github.com/EdurtIO/incubator-dbm/issues/13)
- [x] Support query history Pagination
- [x] Support the construction of data source selection protocol

**Comment by joint-song** [comment]
> - [ ] Add software website
Should we mention website link on README.md?
@qianmoQ

**Comment by qianmoQ** [comment]
> > * [ ]  Add software website
> >   Should we mention website link on README.md?
> >   @qianmoQ

OK

**Comment by joint-song** [comment]
There should be a bug in history pagination.
Re-executed times of sql, the pagination won't refresh correctly.
@qianmoQ

**Comment by qianmoQ** [comment]
> There should be a bug in history pagination.
> Re-executed times of sql, the pagination won't refresh correctly.

Fix

**Comment by qianmoQ** [comment]
Released
