### ISSUE TITLE
Ran command `yarn build` failed on macOS Big Sur

### ISSUE THREAD

**Issue by joint-song** [EdurtIO/incubator-dbm#9]
**Describe the bug**
Running `yarn build` on macOS Big Sur failed.

**To Reproduce**
1. Go to root directory of project.
2. Type `yarn build` and waitting for building.
3. See error:
```
Error: Exit code: 2. Command failed: /usr/bin/perl /private/var/folders/md/tfqt3nvs6fbb4110yq0smqb80000gn/T/t-FPHyHd/1-dmgProperties.pl
Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.2 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at /private/var/folders/md/tfqt3nvs6fbb4110yq0smqb80000gn/T/t-FPHyHd/1-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /private/var/folders/md/tfqt3nvs6fbb4110yq0smqb80000gn/T/t-FPHyHd/1-dmgProperties.pl line 3.

Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module)
```

**Expected behavior**
`yarn build` successfully.

**Screenshots**
No.

**Component (please set component name):**
- Component: yarn
- Version 1.17.3
- Component: npm
- Version 7.19.1
- Component: node
- Version v12.18.2
- Component: macOS
- Version 11.4 (20F71)

**Additional context**
It looks like due to the question of old version of `electron-builder`. Relavant issue: https://github.com/electron-userland/electron-builder/issues/3990. After upgrading `electron-builder` to `"electron-builder": "^21.2.0"`, errors gone.

**Comment by qianmoQ** [comment]
Fix on [commit](https://github.com/EdurtIO/incubator-dbm/commit/81d4b9dac09d53a0a1ac37c78e4ae9cacbed1d11)
